### ISSUE TITLE
Create a session

### ISSUE THREAD

**Issue by viniciusalbuquerque** [DiscordTime/sticky-sessions-android#2]
- [x] Create Firebase Project #13 
- [x] Create Firebase Session Model #17 
- [x] Create Domain Session Model #22 
- [x] Create Mapper between Models #24
~~- [ ] Create Firebase connection #21~~
- [x] Replace remote to retrofit #34 
- [x] Create Use-Case createSession #14
- [x] Rx configuration #9 
- [x] Create Use case and use it from the presenter #33
